import { TranscriptionProvider } from "@/context";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-slate-100")}>
        <Link
          href="/"
          className="mt-6 ml-10 font-serif font-semibold text-2xl block"
        >
          Scribe
        </Link>
        <TranscriptionProvider>{children}</TranscriptionProvider>
      </body>
    </html>
  );
}
